### ISSUE TITLE
Create a dev branch

### ISSUE THREAD

**Issue by alexbocharov** [aspnet/SignalR-Client-Net#3]
Please, create a new development branch for pushing changes to the repository.
I'm ready to make pull request (https://github.com/alexbocharov/SignalR-Client-Net)
/cc @Eilon @davidfowl @DamianEdwards

**Comment by alexbocharov** [comment]
_Steps:_
- [x] Migrate client https://github.com/SignalR/SignalR (as is)
- [ ] Integration dependencies https://github.com/aspnet/Logging (Replacing trace)
- [ ] Integration dependencies https://github.com/aspnet/SignalR-Server (Shared code)

**Comment by Eilon** [comment]
@DamianEdwards thoughts on the priority of this and whether it's actionable right now? I was under the impression we wanted to do some much larger changes than just porting the code to use the new ASP.NET Core types...

**Comment by Eilon** [comment]
cc @davidfowl too

**Comment by alexbocharov** [comment]
@Eilon 
Are you planning to develop from scratch?

**Comment by alexbocharov** [comment]
I did a starting point for further work. What are your plans for work?

**Comment by Eilon** [comment]
@alexbocharov probably not from scratch, but there might be some larger re-designing that we want to do.

**Comment by alexbocharov** [comment]
> @alexbocharov probably not from scratch, but there might be some larger re-designing that we want to do.

@Eilon I started working on it. I change dependences for [SignalR-Server](https://github.com/aspnet/SignalR-Server).

**Next steps:** 
- [ ] Integration [Logging](https://github.com/aspnet/Logging)
- [ ] Integration [SignalR-Server](https://github.com/aspnet/SignalR-Server)
- [ ] Refactoring code

**Comment by Eilon** [comment]
@alexbocharov I understand, but I'm not sure those are the first tasks that need to be tackled. "Refactoring code" is pretty vague.

**Comment by alexbocharov** [comment]
> "Refactoring code" is pretty vague.

@Eilon  I set a goal to remove duplicate code. There are many a duplicate code (Client - Server).

It is the early version of the client.

**Comment by alexbocharov** [comment]
Sorry for my bad English

**Comment by Eilon** [comment]
We would need to discuss with @DamianEdwards and @davidfowl before proceeding.

**Comment by alexbocharov** [comment]
@Eilon Ok. I would be grateful for the direction of future work.
